name: news_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

isar_version: &isar_version 3.1.0+1 # define the version to be used

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  chopper: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.18.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.4
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  share_plus: ^10.0.3
  shared_preferences: ^2.3.2
  
dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.13
  chopper_generator: ^8.0.3
  flutter_test:
    sdk: flutter
  # isar_generator: ^3.1.0+1
  isar_generator: *isar_version
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  
dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
